#!/bin/bash

#   Copyright © 2005 The Regents of the University of California.
#   All Rights Reserved.
#
#   Permission to use, copy, modify, and distribute this software and its
#   documentation for educational, research and non-profit purposes,
#   without fee, and without a written agreement is hereby granted,
#   provided that the above copyright notice, this paragraph and the
#   following three paragraphs appear in all copies.
#
#   Permission to incorporate this software into commercial products may
#   be obtained by contacting the University of California. For
#   information about obtaining such a license contact:
#
#   Chrisanna Waldrop
#   Copyright Officer
#   805-893-7773
#   waldrop@research.ucsb.edu
#
#   This software program and documentation are copyrighted by The Regents
#   of the University of California. The software program and
#   documentation are supplied "as is", without any accompanying services
#   from The Regents. The Regents does not warrant that the operation of
#   the program will be uninterrupted or error-free. The end-user
#   understands that the program was developed for research purposes and
#   is advised not to rely exclusively on the program for any reason.
#
#   IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
#   FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
#   INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
#   ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN
#   ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE UNIVERSITY OF
#   CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT
#   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#   A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS"
#   BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE
#   MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

# Export the paths we need
result=`which text2wfreq 2>&1 | grep -c "no text2wfreq"`

if [ "$result" = 1 ]; then
   echo "Unbable to find CMU CAM Toolkit. Please install and put in you PATH"
   exit 1
fi

if [ "$#" -lt 1 ]; then
   echo "Usage: $0 <caption file>"
   exit 1
fi 

cat $1 | text2wfreq | wfreq2vocab > $1.vocab

# Create the idngram file we need for future commands
cat $1 | text2idngram -n 3 -vocab $1.vocab | idngram2lm -n 3 -vocab $1.vocab -idngram - -arpa $1.arpa 
